export const CLEAR_TRACK_LIST = 'CLEAR_TRACK_LIST'
export const FETCH_TRACKS_FULLFILED = 'FETCH_TRACKS_FULLFILED'

export const TRACKS_ADD_REQUESTED = 'TRACKS_ADD_REQUESTED'
export const TRACKS_ADD_SUCCESS = 'TRACKS_ADD_SUCCESS'
