export const CLEAR_TRACK_LIST = 'CLEAR_TRACK_LIST'
export const FETCH_TRACK_SUCCESS = 'FETCH_TRACKS_SUCCESS'
export const FETCH_TRACK_REQUESTED = 'FETCH_TRACK_REQUESTED'

export const TRACKS_ADD_REQUESTED = 'TRACKS_ADD_REQUESTED'
export const TRACKS_ADD_SUCCESS = 'TRACKS_ADD_SUCCESS'

export const PLAYER_REQUESTED = 'PLAYER_REQUESTED'
export const PLAYER_SUCCESS = 'PLAYER_SUCCESS'
export const HIDE_PLAYER = 'HIDE_PLAYER'
export const SET_PLAYER = 'SET_PLAYER'
export const SHOW_PLAYER = 'SHOW_PLAYER'
export const PLAY = 'PLAY'
export const PAUSE = 'PAUSE'

export const SEARCH_TRACKS_REQUESTED = 'SEARCH_TRACKS_REQUESTED'
export const SEARCH_TRACKS_SUCCESS = 'SEARCH_TRACKS_SUCCESS'
